name: Python CI

on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          pip install pytest
          poetry install
          pip install flake8
          poetry add pytest
      - name: Run linter
        run: |
          poetry build
          make install
          make lint